<?php if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return apply_filters( 'ninja_forms_uploads_field_settings', array(
	'save_to_server' => array(
		'name'  => 'save_to_server',
		'type'  => 'toggle',
		'value' => '1',
		'label' =>  'Save to Server',
		'group' => 'primary',
		'width' => 'one-half',
		'help'  =>  'Save the file to the server.',
	),
	'upload_rename' => array(
		'name'           => 'upload_rename',
		'type'           => 'textbox',
		'value'          => '',
		'label'          =>  'Rename Uploaded File',
		'group'          => 'primary',
		'width'          => 'full',
		'help'           =>  'Advanced renaming options. You can also create directories using "/". If you do not want to rename the files, leave this box blank',
		'use_merge_tags' => true,
	),
	'media_library' => array(
		'name'  => 'media_library',
		'type'  => 'toggle',
		'value' => 'false',
		'label' =>  'Save to Media Library',
		'group' => 'primary',
		'width' => 'one-half',
		'help'  =>  'Save to Media Library.',
		'deps'  => array(
			'save_to_server' => true,
		),
	),
	'upload_multi_count' => array(
		'name'  => 'upload_multi_count',
		'type'  => 'number',
		'label' =>  'File Limit',
		'value' => 1,
		'width' => 'one-half',
		'group' => 'restrictions',
		'help'  =>  'How many files can be uploaded?',
	),
	'upload_types'       => array(
		'name'        => 'upload_types',
		'type'        => 'textarea',
		'label'       =>  'Allowed File Types',
		'help'        =>  'Comma Separated List of allowed file types. Leaving the option empty will restore the default list. (i.e. jpg, gif, png, pdf) This is not fool-proof and can be tricked, please remember that there is always a danger in allowing users to upload files.',
		'group'       => 'restrictions',
		'width'       => 'one-half',
	),
	'max_file_size' => array(
		'name'  => 'max_file_size',
		'type'  => 'number',
		'label' =>  'Maximum File Size (MB)',
		'value' => '',
		'width' => 'one-half',
		'group' => 'restrictions',
		'help'  =>  'Maximum size of a file that can be uploaded.',
	),
	'min_file_size' => array(
		'name'  => 'min_file_size',
		'type'  => 'number',
		'label' =>  'Minimum File Size (MB)',
		'value' => '0',
		'width' => 'one-half',
		'group' => 'restrictions',
		'help'  =>  'Minimum size of a file that can be uploaded.',
	),
	'select_files_text' => array(
		'name'  => 'select_files_text',
		'type'  => 'textbox',
		'value' =>  'Select Files',
		'label' =>  'Select Files Button Text',
		'group' => 'display',
		'width' => 'full',
		'help'  =>  'Change the button text for selecting files.',
	),
	'cancel_upload_text' => array(
		'name'  => 'cancel_upload_text',
		'type'  => 'textbox',
		'value' =>  'Cancel',
		'label' =>  'Cancel File Upload Button Text',
		'group' => 'display',
		'width' => 'full',
		'help'  =>  'Change the button text for cancelling uploads.',
	),
) );
